version: '3'
services:
    redis-server:
        image: 'redis'
    node-app:
        # restart: always
        # look in current directory for dockerfile
        build: .
        ports:
            - "4001:8081"

